// Code generated by mockery v1.0.0. DO NOT EDIT.

package oauth

import (
	mock "github.com/stretchr/testify/mock"
	integrations "github.com/toggl/pipes-api/pkg/integrations"

	"code.google.com/p/goauth2/oauth"
	oauthplain "github.com/tambet/oauthplain"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

// OAuth1Configs provides a mock function with given fields: _a0
func (_m *MockProvider) OAuth1Configs(_a0 integrations.ExternalServiceID) (*oauthplain.Config, bool) {
	ret := _m.Called(_a0)

	var r0 *oauthplain.Config
	if rf, ok := ret.Get(0).(func(integrations.ExternalServiceID) *oauthplain.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauthplain.Config)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(integrations.ExternalServiceID) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// OAuth1Exchange provides a mock function with given fields: _a0, _a1
func (_m *MockProvider) OAuth1Exchange(_a0 integrations.ExternalServiceID, _a1 ParamsV1) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(integrations.ExternalServiceID, ParamsV1) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integrations.ExternalServiceID, ParamsV1) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OAuth2Configs provides a mock function with given fields: _a0
func (_m *MockProvider) OAuth2Configs(_a0 integrations.ExternalServiceID) (*oauth.Config, bool) {
	ret := _m.Called(_a0)

	var r0 *oauth.Config
	if rf, ok := ret.Get(0).(func(integrations.ExternalServiceID) *oauth.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.Config)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(integrations.ExternalServiceID) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// OAuth2Exchange provides a mock function with given fields: _a0, _a1
func (_m *MockProvider) OAuth2Exchange(_a0 integrations.ExternalServiceID, _a1 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(integrations.ExternalServiceID, string) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integrations.ExternalServiceID, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OAuth2Refresh provides a mock function with given fields: _a0, _a1
func (_m *MockProvider) OAuth2Refresh(_a0 *oauth.Config, _a1 *oauth.Token) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*oauth.Config, *oauth.Token) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OAuth2URL provides a mock function with given fields: _a0
func (_m *MockProvider) OAuth2URL(_a0 integrations.ExternalServiceID) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(integrations.ExternalServiceID) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
