// Code generated by mockery v1.0.0. DO NOT EDIT.

package pipe

import mock "github.com/stretchr/testify/mock"

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

// GetPipesFromQueue provides a mock function with given fields:
func (_m *MockQueue) GetPipesFromQueue() ([]*Pipe, error) {
	ret := _m.Called()

	var r0 []*Pipe
	if rf, ok := ret.Get(0).(func() []*Pipe); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueueAutomaticPipes provides a mock function with given fields:
func (_m *MockQueue) QueueAutomaticPipes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetQueuedPipeSynced provides a mock function with given fields: _a0
func (_m *MockQueue) SetQueuedPipeSynced(_a0 *Pipe) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Pipe) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
