// Code generated by mockery v1.0.0. DO NOT EDIT.

package pipe

import mock "github.com/stretchr/testify/mock"

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0
func (_m *MockRunner) Run(_a0 *Pipe) {
	_m.Called(_a0)
}
