// Code generated by mockery v1.0.0. DO NOT EDIT.

package pipe

import integrations "github.com/toggl/pipes-api/pkg/integrations"
import mock "github.com/stretchr/testify/mock"
import toggl "github.com/toggl/pipes-api/pkg/toggl"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// ClearImportFor provides a mock function with given fields: s, pid
func (_m *MockStorage) ClearImportFor(s integrations.ExternalService, pid integrations.PipeID) error {
	ret := _m.Called(s, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(integrations.ExternalService, integrations.PipeID) error); ok {
		r0 = rf(s, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: p, workspaceID
func (_m *MockStorage) Delete(p *Pipe, workspaceID int) error {
	ret := _m.Called(p, workspaceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Pipe, int) error); ok {
		r0 = rf(p, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAuthorization provides a mock function with given fields: workspaceID, externalServiceID
func (_m *MockStorage) DeleteAuthorization(workspaceID int, externalServiceID integrations.ExternalServiceID) error {
	ret := _m.Called(workspaceID, externalServiceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integrations.ExternalServiceID) error); ok {
		r0 = rf(workspaceID, externalServiceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePipeByWorkspaceIDServiceID provides a mock function with given fields: workspaceID, sid
func (_m *MockStorage) DeletePipeByWorkspaceIDServiceID(workspaceID int, sid integrations.ExternalServiceID) error {
	ret := _m.Called(workspaceID, sid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integrations.ExternalServiceID) error); ok {
		r0 = rf(workspaceID, sid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePipeConnections provides a mock function with given fields: workspaceID, pipeConnectionKey, pipeStatusKey
func (_m *MockStorage) DeletePipeConnections(workspaceID int, pipeConnectionKey string, pipeStatusKey string) error {
	ret := _m.Called(workspaceID, pipeConnectionKey, pipeStatusKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = rf(workspaceID, pipeConnectionKey, pipeStatusKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPipesFromQueue provides a mock function with given fields:
func (_m *MockStorage) GetPipesFromQueue() ([]*Pipe, error) {
	ret := _m.Called()

	var r0 []*Pipe
	if rf, ok := ret.Get(0).(func() []*Pipe); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsDown provides a mock function with given fields:
func (_m *MockStorage) IsDown() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LoadAccounts provides a mock function with given fields: s
func (_m *MockStorage) LoadAccounts(s integrations.ExternalService) (*toggl.AccountsResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.AccountsResponse
	if rf, ok := ret.Get(0).(func(integrations.ExternalService) *toggl.AccountsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.AccountsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integrations.ExternalService) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAuthorization provides a mock function with given fields: workspaceID, sid
func (_m *MockStorage) LoadAuthorization(workspaceID int, sid integrations.ExternalServiceID) (*Authorization, error) {
	ret := _m.Called(workspaceID, sid)

	var r0 *Authorization
	if rf, ok := ret.Get(0).(func(int, integrations.ExternalServiceID) *Authorization); ok {
		r0 = rf(workspaceID, sid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Authorization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integrations.ExternalServiceID) error); ok {
		r1 = rf(workspaceID, sid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadConnection provides a mock function with given fields: workspaceID, key
func (_m *MockStorage) LoadConnection(workspaceID int, key string) (*Connection, error) {
	ret := _m.Called(workspaceID, key)

	var r0 *Connection
	if rf, ok := ret.Get(0).(func(int, string) *Connection); ok {
		r0 = rf(workspaceID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Connection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(workspaceID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadLastSync provides a mock function with given fields: p
func (_m *MockStorage) LoadLastSync(p *Pipe) {
	_m.Called(p)
}

// LoadObject provides a mock function with given fields: s, pid
func (_m *MockStorage) LoadObject(s integrations.ExternalService, pid integrations.PipeID) ([]byte, error) {
	ret := _m.Called(s, pid)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(integrations.ExternalService, integrations.PipeID) []byte); ok {
		r0 = rf(s, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integrations.ExternalService, integrations.PipeID) error); ok {
		r1 = rf(s, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPipe provides a mock function with given fields: workspaceID, sid, pid
func (_m *MockStorage) LoadPipe(workspaceID int, sid integrations.ExternalServiceID, pid integrations.PipeID) (*Pipe, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 *Pipe
	if rf, ok := ret.Get(0).(func(int, integrations.ExternalServiceID, integrations.PipeID) *Pipe); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integrations.ExternalServiceID, integrations.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPipeStatus provides a mock function with given fields: workspaceID, sid, pid
func (_m *MockStorage) LoadPipeStatus(workspaceID int, sid integrations.ExternalServiceID, pid integrations.PipeID) (*Status, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 *Status
	if rf, ok := ret.Get(0).(func(int, integrations.ExternalServiceID, integrations.PipeID) *Status); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integrations.ExternalServiceID, integrations.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPipeStatuses provides a mock function with given fields: workspaceID
func (_m *MockStorage) LoadPipeStatuses(workspaceID int) (map[string]*Status, error) {
	ret := _m.Called(workspaceID)

	var r0 map[string]*Status
	if rf, ok := ret.Get(0).(func(int) map[string]*Status); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPipes provides a mock function with given fields: workspaceID
func (_m *MockStorage) LoadPipes(workspaceID int) (map[string]*Pipe, error) {
	ret := _m.Called(workspaceID)

	var r0 map[string]*Pipe
	if rf, ok := ret.Get(0).(func(int) map[string]*Pipe); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadReversedConnection provides a mock function with given fields: workspaceID, key
func (_m *MockStorage) LoadReversedConnection(workspaceID int, key string) (*ReversedConnection, error) {
	ret := _m.Called(workspaceID, key)

	var r0 *ReversedConnection
	if rf, ok := ret.Get(0).(func(int, string) *ReversedConnection); ok {
		r0 = rf(workspaceID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReversedConnection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(workspaceID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadWorkspaceAuthorizations provides a mock function with given fields: workspaceID
func (_m *MockStorage) LoadWorkspaceAuthorizations(workspaceID int) (map[integrations.ExternalServiceID]bool, error) {
	ret := _m.Called(workspaceID)

	var r0 map[integrations.ExternalServiceID]bool
	if rf, ok := ret.Get(0).(func(int) map[integrations.ExternalServiceID]bool); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[integrations.ExternalServiceID]bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueueAutomaticPipes provides a mock function with given fields:
func (_m *MockStorage) QueueAutomaticPipes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueuePipeAsFirst provides a mock function with given fields: _a0
func (_m *MockStorage) QueuePipeAsFirst(_a0 *Pipe) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Pipe) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: p
func (_m *MockStorage) Save(p *Pipe) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Pipe) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAccounts provides a mock function with given fields: s
func (_m *MockStorage) SaveAccounts(s integrations.ExternalService) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(integrations.ExternalService) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAuthorization provides a mock function with given fields: a
func (_m *MockStorage) SaveAuthorization(a *Authorization) error {
	ret := _m.Called(a)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Authorization) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveConnection provides a mock function with given fields: c
func (_m *MockStorage) SaveConnection(c *Connection) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Connection) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveObject provides a mock function with given fields: s, pid, obj
func (_m *MockStorage) SaveObject(s integrations.ExternalService, pid integrations.PipeID, obj interface{}) error {
	ret := _m.Called(s, pid, obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(integrations.ExternalService, integrations.PipeID, interface{}) error); ok {
		r0 = rf(s, pid, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SavePipeStatus provides a mock function with given fields: p
func (_m *MockStorage) SavePipeStatus(p *Status) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Status) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetQueuedPipeSynced provides a mock function with given fields: _a0
func (_m *MockStorage) SetQueuedPipeSynced(_a0 *Pipe) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Pipe) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
