// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import pipe "github.com/toggl/pipes-api/pkg/pipe"

// QueueRunner is an autogenerated mock type for the QueueRunner type
type QueueRunner struct {
	mock.Mock
}

// GetPipesFromQueue provides a mock function with given fields:
func (_m *QueueRunner) GetPipesFromQueue() ([]*pipe.Pipe, error) {
	ret := _m.Called()

	var r0 []*pipe.Pipe
	if rf, ok := ret.Get(0).(func() []*pipe.Pipe); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pipe.Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueueAutomaticPipes provides a mock function with given fields:
func (_m *QueueRunner) QueueAutomaticPipes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields: _a0
func (_m *QueueRunner) Run(_a0 *pipe.Pipe) {
	_m.Called(_a0)
}

// SetQueuedPipeSynced provides a mock function with given fields: _a0
func (_m *QueueRunner) SetQueuedPipeSynced(_a0 *pipe.Pipe) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*pipe.Pipe) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
