// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pipe "github.com/toggl/pipes-api/pkg/pipe"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0
func (_m *Runner) Run(_a0 *pipe.Pipe) {
	_m.Called(_a0)
}
