// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	integration "github.com/toggl/pipes-api/pkg/integration"

	pipe "github.com/toggl/pipes-api/pkg/pipe"

	toggl "github.com/toggl/pipes-api/pkg/toggl"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ClearIDMappings provides a mock function with given fields: workspaceID, sid, pid
func (_m *Service) ClearIDMappings(workspaceID int, sid integration.ID, pid integration.PipeID) error {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID) error); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAuthorization provides a mock function with given fields: workspaceID, sid, workspaceToken, params
func (_m *Service) CreateAuthorization(workspaceID int, sid integration.ID, workspaceToken string, params pipe.AuthParams) error {
	ret := _m.Called(workspaceID, sid, workspaceToken, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID, string, pipe.AuthParams) error); ok {
		r0 = rf(workspaceID, sid, workspaceToken, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePipe provides a mock function with given fields: workspaceID, sid, pid, params
func (_m *Service) CreatePipe(workspaceID int, sid integration.ID, pid integration.PipeID, params []byte) error {
	ret := _m.Called(workspaceID, sid, pid, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID, []byte) error); ok {
		r0 = rf(workspaceID, sid, pid, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAuthorization provides a mock function with given fields: workspaceID, sid
func (_m *Service) DeleteAuthorization(workspaceID int, sid integration.ID) error {
	ret := _m.Called(workspaceID, sid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID) error); ok {
		r0 = rf(workspaceID, sid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePipe provides a mock function with given fields: workspaceID, sid, pid
func (_m *Service) DeletePipe(workspaceID int, sid integration.ID, pid integration.PipeID) error {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID) error); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthURL provides a mock function with given fields: sid, accountName, callbackURL
func (_m *Service) GetAuthURL(sid integration.ID, accountName string, callbackURL string) (string, error) {
	ret := _m.Called(sid, accountName, callbackURL)

	var r0 string
	if rf, ok := ret.Get(0).(func(integration.ID, string, string) string); ok {
		r0 = rf(sid, accountName, callbackURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.ID, string, string) error); ok {
		r1 = rf(sid, accountName, callbackURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIntegrations provides a mock function with given fields: workspaceID
func (_m *Service) GetIntegrations(workspaceID int) ([]pipe.Integration, error) {
	ret := _m.Called(workspaceID)

	var r0 []pipe.Integration
	if rf, ok := ret.Get(0).(func(int) []pipe.Integration); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pipe.Integration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPipe provides a mock function with given fields: workspaceID, sid, pid
func (_m *Service) GetPipe(workspaceID int, sid integration.ID, pid integration.PipeID) (*pipe.Pipe, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 *pipe.Pipe
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID) *pipe.Pipe); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pipe.Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integration.ID, integration.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceAccounts provides a mock function with given fields: workspaceID, sid, forceImport
func (_m *Service) GetServiceAccounts(workspaceID int, sid integration.ID, forceImport bool) (*toggl.AccountsResponse, error) {
	ret := _m.Called(workspaceID, sid, forceImport)

	var r0 *toggl.AccountsResponse
	if rf, ok := ret.Get(0).(func(int, integration.ID, bool) *toggl.AccountsResponse); ok {
		r0 = rf(workspaceID, sid, forceImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.AccountsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integration.ID, bool) error); ok {
		r1 = rf(workspaceID, sid, forceImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServicePipeLog provides a mock function with given fields: workspaceID, sid, pid
func (_m *Service) GetServicePipeLog(workspaceID int, sid integration.ID, pid integration.PipeID) (string, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID) string); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integration.ID, integration.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceUsers provides a mock function with given fields: workspaceID, sid, forceImport
func (_m *Service) GetServiceUsers(workspaceID int, sid integration.ID, forceImport bool) (*toggl.UsersResponse, error) {
	ret := _m.Called(workspaceID, sid, forceImport)

	var r0 *toggl.UsersResponse
	if rf, ok := ret.Get(0).(func(int, integration.ID, bool) *toggl.UsersResponse); ok {
		r0 = rf(workspaceID, sid, forceImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.UsersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, integration.ID, bool) error); ok {
		r1 = rf(workspaceID, sid, forceImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ready provides a mock function with given fields:
func (_m *Service) Ready() []error {
	ret := _m.Called()

	var r0 []error
	if rf, ok := ret.Get(0).(func() []error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// Run provides a mock function with given fields: _a0
func (_m *Service) Run(_a0 *pipe.Pipe) {
	_m.Called(_a0)
}

// RunPipe provides a mock function with given fields: workspaceID, sid, pid, usersSelector
func (_m *Service) RunPipe(workspaceID int, sid integration.ID, pid integration.PipeID, usersSelector []byte) error {
	ret := _m.Called(workspaceID, sid, pid, usersSelector)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID, []byte) error); ok {
		r0 = rf(workspaceID, sid, pid, usersSelector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePipe provides a mock function with given fields: workspaceID, sid, pid, params
func (_m *Service) UpdatePipe(workspaceID int, sid integration.ID, pid integration.PipeID, params []byte) error {
	ret := _m.Called(workspaceID, sid, pid, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, integration.ID, integration.PipeID, []byte) error); ok {
		r0 = rf(workspaceID, sid, pid, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
