// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HealthCheckService is an autogenerated mock type for the HealthCheckService type
type HealthCheckService struct {
	mock.Mock
}

// Ready provides a mock function with given fields:
func (_m *HealthCheckService) Ready() []error {
	ret := _m.Called()

	var r0 []error
	if rf, ok := ret.Get(0).(func() []error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}
