// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/toggl/pipes-api/pkg/domain"
)

// ImportsStorage is an autogenerated mock type for the ImportsStorage type
type ImportsStorage struct {
	mock.Mock
}

// DeleteAccountsFor provides a mock function with given fields: s
func (_m *ImportsStorage) DeleteAccountsFor(s domain.PipeIntegration) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUsersFor provides a mock function with given fields: s
func (_m *ImportsStorage) DeleteUsersFor(s domain.PipeIntegration) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadAccountsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadAccountsFor(s domain.PipeIntegration) (*domain.AccountsResponse, error) {
	ret := _m.Called(s)

	var r0 *domain.AccountsResponse
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) *domain.AccountsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccountsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PipeIntegration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadClientsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadClientsFor(s domain.PipeIntegration) (*domain.ClientsResponse, error) {
	ret := _m.Called(s)

	var r0 *domain.ClientsResponse
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) *domain.ClientsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ClientsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PipeIntegration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadProjectsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadProjectsFor(s domain.PipeIntegration) (*domain.ProjectsResponse, error) {
	ret := _m.Called(s)

	var r0 *domain.ProjectsResponse
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) *domain.ProjectsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PipeIntegration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadTasksFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadTasksFor(s domain.PipeIntegration) (*domain.TasksResponse, error) {
	ret := _m.Called(s)

	var r0 *domain.TasksResponse
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) *domain.TasksResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TasksResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PipeIntegration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadTodoListsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadTodoListsFor(s domain.PipeIntegration) (*domain.TasksResponse, error) {
	ret := _m.Called(s)

	var r0 *domain.TasksResponse
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) *domain.TasksResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TasksResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PipeIntegration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadUsersFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadUsersFor(s domain.PipeIntegration) (*domain.UsersResponse, error) {
	ret := _m.Called(s)

	var r0 *domain.UsersResponse
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration) *domain.UsersResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UsersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PipeIntegration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAccountsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveAccountsFor(s domain.PipeIntegration, res domain.AccountsResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration, domain.AccountsResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveClientsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveClientsFor(s domain.PipeIntegration, res domain.ClientsResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration, domain.ClientsResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveProjectsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveProjectsFor(s domain.PipeIntegration, res domain.ProjectsResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration, domain.ProjectsResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTasksFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveTasksFor(s domain.PipeIntegration, res domain.TasksResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration, domain.TasksResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTodoListsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveTodoListsFor(s domain.PipeIntegration, res domain.TasksResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration, domain.TasksResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUsersFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveUsersFor(s domain.PipeIntegration, res domain.UsersResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.PipeIntegration, domain.UsersResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
