// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	integration "github.com/toggl/pipes-api/pkg/integration"

	toggl "github.com/toggl/pipes-api/pkg/toggl"
)

// ImportsStorage is an autogenerated mock type for the ImportsStorage type
type ImportsStorage struct {
	mock.Mock
}

// DeleteAccountsFor provides a mock function with given fields: s
func (_m *ImportsStorage) DeleteAccountsFor(s integration.Integration) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUsersFor provides a mock function with given fields: s
func (_m *ImportsStorage) DeleteUsersFor(s integration.Integration) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadAccountsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadAccountsFor(s integration.Integration) (*toggl.AccountsResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.AccountsResponse
	if rf, ok := ret.Get(0).(func(integration.Integration) *toggl.AccountsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.AccountsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.Integration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadClientsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadClientsFor(s integration.Integration) (*toggl.ClientsResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.ClientsResponse
	if rf, ok := ret.Get(0).(func(integration.Integration) *toggl.ClientsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.ClientsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.Integration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadProjectsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadProjectsFor(s integration.Integration) (*toggl.ProjectsResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.ProjectsResponse
	if rf, ok := ret.Get(0).(func(integration.Integration) *toggl.ProjectsResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.ProjectsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.Integration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadTasksFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadTasksFor(s integration.Integration) (*toggl.TasksResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.TasksResponse
	if rf, ok := ret.Get(0).(func(integration.Integration) *toggl.TasksResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.TasksResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.Integration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadTodoListsFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadTodoListsFor(s integration.Integration) (*toggl.TasksResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.TasksResponse
	if rf, ok := ret.Get(0).(func(integration.Integration) *toggl.TasksResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.TasksResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.Integration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadUsersFor provides a mock function with given fields: s
func (_m *ImportsStorage) LoadUsersFor(s integration.Integration) (*toggl.UsersResponse, error) {
	ret := _m.Called(s)

	var r0 *toggl.UsersResponse
	if rf, ok := ret.Get(0).(func(integration.Integration) *toggl.UsersResponse); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*toggl.UsersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(integration.Integration) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAccountsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveAccountsFor(s integration.Integration, res toggl.AccountsResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration, toggl.AccountsResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveClientsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveClientsFor(s integration.Integration, res toggl.ClientsResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration, toggl.ClientsResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveProjectsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveProjectsFor(s integration.Integration, res toggl.ProjectsResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration, toggl.ProjectsResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTasksFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveTasksFor(s integration.Integration, res toggl.TasksResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration, toggl.TasksResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTodoListsFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveTodoListsFor(s integration.Integration, res toggl.TasksResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration, toggl.TasksResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUsersFor provides a mock function with given fields: s, res
func (_m *ImportsStorage) SaveUsersFor(s integration.Integration, res toggl.UsersResponse) error {
	ret := _m.Called(s, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(integration.Integration, toggl.UsersResponse) error); ok {
		r0 = rf(s, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
