// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/toggl/pipes-api/pkg/domain"
)

// IntegrationsStorage is an autogenerated mock type for the IntegrationsStorage type
type IntegrationsStorage struct {
	mock.Mock
}

// IsValidPipe provides a mock function with given fields: pipeID
func (_m *IntegrationsStorage) IsValidPipe(pipeID domain.PipeID) bool {
	ret := _m.Called(pipeID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(domain.PipeID) bool); ok {
		r0 = rf(pipeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsValidService provides a mock function with given fields: serviceID
func (_m *IntegrationsStorage) IsValidService(serviceID domain.ID) bool {
	ret := _m.Called(serviceID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(domain.ID) bool); ok {
		r0 = rf(serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LoadAuthorizationType provides a mock function with given fields: serviceID
func (_m *IntegrationsStorage) LoadAuthorizationType(serviceID domain.ID) (string, error) {
	ret := _m.Called(serviceID)

	var r0 string
	if rf, ok := ret.Get(0).(func(domain.ID) string); ok {
		r0 = rf(serviceID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.ID) error); ok {
		r1 = rf(serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadIntegrations provides a mock function with given fields:
func (_m *IntegrationsStorage) LoadIntegrations() ([]*domain.Integration, error) {
	ret := _m.Called()

	var r0 []*domain.Integration
	if rf, ok := ret.Get(0).(func() []*domain.Integration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Integration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAuthorizationType provides a mock function with given fields: serviceID, authType
func (_m *IntegrationsStorage) SaveAuthorizationType(serviceID domain.ID, authType string) error {
	ret := _m.Called(serviceID, authType)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ID, string) error); ok {
		r0 = rf(serviceID, authType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
