// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/toggl/pipes-api/pkg/domain"
)

// PipesStorage is an autogenerated mock type for the PipesStorage type
type PipesStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: p, workspaceID
func (_m *PipesStorage) Delete(p *domain.Pipe, workspaceID int) error {
	ret := _m.Called(p, workspaceID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Pipe, int) error); ok {
		r0 = rf(p, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByWorkspaceIDServiceID provides a mock function with given fields: workspaceID, sid
func (_m *PipesStorage) DeleteByWorkspaceIDServiceID(workspaceID int, sid domain.ID) error {
	ret := _m.Called(workspaceID, sid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.ID) error); ok {
		r0 = rf(workspaceID, sid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsDown provides a mock function with given fields:
func (_m *PipesStorage) IsDown() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Load provides a mock function with given fields: p
func (_m *PipesStorage) Load(p *domain.Pipe) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Pipe) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadAll provides a mock function with given fields: workspaceID
func (_m *PipesStorage) LoadAll(workspaceID int) (map[string]*domain.Pipe, error) {
	ret := _m.Called(workspaceID)

	var r0 map[string]*domain.Pipe
	if rf, ok := ret.Get(0).(func(int) map[string]*domain.Pipe); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAllStatuses provides a mock function with given fields: workspaceID
func (_m *PipesStorage) LoadAllStatuses(workspaceID int) (map[string]*domain.Status, error) {
	ret := _m.Called(workspaceID)

	var r0 map[string]*domain.Status
	if rf, ok := ret.Get(0).(func(int) map[string]*domain.Status); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*domain.Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadLastSyncFor provides a mock function with given fields: p
func (_m *PipesStorage) LoadLastSyncFor(p *domain.Pipe) {
	_m.Called(p)
}

// LoadStatus provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipesStorage) LoadStatus(workspaceID int, sid domain.ID, pid domain.PipeID) (*domain.Status, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 *domain.Status
	if rf, ok := ret.Get(0).(func(int, domain.ID, domain.PipeID) *domain.Status); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.ID, domain.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: p
func (_m *PipesStorage) Save(p *domain.Pipe) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Pipe) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveStatus provides a mock function with given fields: p
func (_m *PipesStorage) SaveStatus(p *domain.Status) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Status) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
