// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/toggl/pipes-api/pkg/domain"
)

// PipeService is an autogenerated mock type for the PipeService type
type PipeService struct {
	mock.Mock
}

// ClearIDMappings provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipeService) ClearIDMappings(workspaceID int, sid domain.IntegrationID, pid domain.PipeID) error {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID) error); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAuthorization provides a mock function with given fields: workspaceID, sid, workspaceToken, params
func (_m *PipeService) CreateAuthorization(workspaceID int, sid domain.IntegrationID, workspaceToken string, params domain.AuthParams) error {
	ret := _m.Called(workspaceID, sid, workspaceToken, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, string, domain.AuthParams) error); ok {
		r0 = rf(workspaceID, sid, workspaceToken, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePipe provides a mock function with given fields: workspaceID, sid, pid, params
func (_m *PipeService) CreatePipe(workspaceID int, sid domain.IntegrationID, pid domain.PipeID, params []byte) error {
	ret := _m.Called(workspaceID, sid, pid, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID, []byte) error); ok {
		r0 = rf(workspaceID, sid, pid, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAuthorization provides a mock function with given fields: workspaceID, sid
func (_m *PipeService) DeleteAuthorization(workspaceID int, sid domain.IntegrationID) error {
	ret := _m.Called(workspaceID, sid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID) error); ok {
		r0 = rf(workspaceID, sid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePipe provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipeService) DeletePipe(workspaceID int, sid domain.IntegrationID, pid domain.PipeID) error {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID) error); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthURL provides a mock function with given fields: sid, accountName, callbackURL
func (_m *PipeService) GetAuthURL(sid domain.IntegrationID, accountName string, callbackURL string) (string, error) {
	ret := _m.Called(sid, accountName, callbackURL)

	var r0 string
	if rf, ok := ret.Get(0).(func(domain.IntegrationID, string, string) string); ok {
		r0 = rf(sid, accountName, callbackURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.IntegrationID, string, string) error); ok {
		r1 = rf(sid, accountName, callbackURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIntegrations provides a mock function with given fields: workspaceID
func (_m *PipeService) GetIntegrations(workspaceID int) ([]domain.Integration, error) {
	ret := _m.Called(workspaceID)

	var r0 []domain.Integration
	if rf, ok := ret.Get(0).(func(int) []domain.Integration); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Integration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPipe provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipeService) GetPipe(workspaceID int, sid domain.IntegrationID, pid domain.PipeID) (*domain.Pipe, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 *domain.Pipe
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID) *domain.Pipe); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Pipe)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, domain.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceAccounts provides a mock function with given fields: workspaceID, sid, forceImport
func (_m *PipeService) GetServiceAccounts(workspaceID int, sid domain.IntegrationID, forceImport bool) (*domain.AccountsResponse, error) {
	ret := _m.Called(workspaceID, sid, forceImport)

	var r0 *domain.AccountsResponse
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, bool) *domain.AccountsResponse); ok {
		r0 = rf(workspaceID, sid, forceImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccountsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, bool) error); ok {
		r1 = rf(workspaceID, sid, forceImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServicePipeLog provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipeService) GetServicePipeLog(workspaceID int, sid domain.IntegrationID, pid domain.PipeID) (string, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID) string); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, domain.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceUsers provides a mock function with given fields: workspaceID, sid, forceImport
func (_m *PipeService) GetServiceUsers(workspaceID int, sid domain.IntegrationID, forceImport bool) (*domain.UsersResponse, error) {
	ret := _m.Called(workspaceID, sid, forceImport)

	var r0 *domain.UsersResponse
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, bool) *domain.UsersResponse); ok {
		r0 = rf(workspaceID, sid, forceImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UsersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, bool) error); ok {
		r1 = rf(workspaceID, sid, forceImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ready provides a mock function with given fields:
func (_m *PipeService) Ready() []error {
	ret := _m.Called()

	var r0 []error
	if rf, ok := ret.Get(0).(func() []error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// Synchronize provides a mock function with given fields: p
func (_m *PipeService) Synchronize(p *domain.Pipe) {
	_m.Called(p)
}

// UpdatePipe provides a mock function with given fields: workspaceID, sid, pid, params
func (_m *PipeService) UpdatePipe(workspaceID int, sid domain.IntegrationID, pid domain.PipeID, params []byte) error {
	ret := _m.Called(workspaceID, sid, pid, params)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID, []byte) error); ok {
		r0 = rf(workspaceID, sid, pid, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
