// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/toggl/pipes-api/pkg/domain"
)

// PipeSyncService is an autogenerated mock type for the PipeSyncService type
type PipeSyncService struct {
	mock.Mock
}

// ClearIDMappings provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipeSyncService) ClearIDMappings(workspaceID int, sid domain.IntegrationID, pid domain.PipeID) error {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID) error); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetIntegrations provides a mock function with given fields: workspaceID
func (_m *PipeSyncService) GetIntegrations(workspaceID int) ([]domain.Integration, error) {
	ret := _m.Called(workspaceID)

	var r0 []domain.Integration
	if rf, ok := ret.Get(0).(func(int) []domain.Integration); ok {
		r0 = rf(workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Integration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceAccounts provides a mock function with given fields: workspaceID, sid, forceImport
func (_m *PipeSyncService) GetServiceAccounts(workspaceID int, sid domain.IntegrationID, forceImport bool) (*domain.AccountsResponse, error) {
	ret := _m.Called(workspaceID, sid, forceImport)

	var r0 *domain.AccountsResponse
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, bool) *domain.AccountsResponse); ok {
		r0 = rf(workspaceID, sid, forceImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccountsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, bool) error); ok {
		r1 = rf(workspaceID, sid, forceImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServicePipeLog provides a mock function with given fields: workspaceID, sid, pid
func (_m *PipeSyncService) GetServicePipeLog(workspaceID int, sid domain.IntegrationID, pid domain.PipeID) (string, error) {
	ret := _m.Called(workspaceID, sid, pid)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, domain.PipeID) string); ok {
		r0 = rf(workspaceID, sid, pid)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, domain.PipeID) error); ok {
		r1 = rf(workspaceID, sid, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceUsers provides a mock function with given fields: workspaceID, sid, forceImport
func (_m *PipeSyncService) GetServiceUsers(workspaceID int, sid domain.IntegrationID, forceImport bool) (*domain.UsersResponse, error) {
	ret := _m.Called(workspaceID, sid, forceImport)

	var r0 *domain.UsersResponse
	if rf, ok := ret.Get(0).(func(int, domain.IntegrationID, bool) *domain.UsersResponse); ok {
		r0 = rf(workspaceID, sid, forceImport)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UsersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.IntegrationID, bool) error); ok {
		r1 = rf(workspaceID, sid, forceImport)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Synchronize provides a mock function with given fields: p
func (_m *PipeSyncService) Synchronize(p *domain.Pipe) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Pipe) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
